apiVersion: argoproj.io/v1alpha1  
kind: ApplicationSet  
metadata:  
  name: podinfo  
spec:  
  generators:  
    - git:  
        repoURL: https://github.com/dewandemo/applicationset.git  
        revision: HEAD  
        files:  
        - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"  
  template:  
    metadata:  
      name: '{{cluster.name}}-podinfo'  
    spec:  
      project: 574b932a  
      source:  
        repoURL: https://github.com/dewandemo/applicationset.git  
        targetRevision: HEAD  
        path: "examples/git-generator-files-discovery/apps/podinfo"  
      destination:  
        server: '{{cluster.address}}'  
        namespace: default  
      syncPolicy:  
        automated: {}
